# .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'        # Exclude all files in the bin directory
    - 'db/schema.rb' # Exclude db/schema.rb
    - 'db/migrate/*'
    - 'lib/tasks/*'  # Exclude all files in the lib/tasks directory
    - 'spec/support/**/*' # Exclude all files in the spec/support directory and subdirectories